version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run: |
          ls runTest.sh
          node --version
          npm -v

# Orchestrate our job run sequence
workflows:
  run_test:
        jobs:
          - test
