version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run: 
          echo "this is the test job"
          echo "this is the 2nd line"

# Orchestrate our job run sequence
workflows:
  run_test:
        jobs:
          - test
