version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  run_test:
        jobs:
          - test
