version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run: | 
           ls runTest.sh


# Orchestrate our job run sequence
workflows:
  run_test:
        jobs:
          - test
