version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run: | 
           sudo npm install -g newman
           ls runTest.sh
           chmod +x runTest.sh
           ./runTest.sh

# Orchestrate our job run sequence
workflows:
  run_test:
        jobs:
          - test
