version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run: |
          ls runTest.sh
          node --version
          npm -v
          sudo npm install -g newman
          sudo npm install -g newman-reporter-html
          sudo npm install -g newman-reporter-htmlextra
          chmod +x runTest.sh
          ./runTest.sh
          ls newman/*
      - store_artifacts:
          path: newman
          destination: newman_result.html
      

# Orchestrate our job run sequence
workflows:
  run_test:
        jobs:
          - test
